spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

    # just for debugging
    #  jpa:
    #    show-sql: true

server:
  port: 8080

  ssl:
    key-store-type: PKCS12
    key-store: bettertest.p12
    key-store-password: RegIT-Better
    key-alias: bettertest

  error:
    whitelabel:
      enabled: false

logging:
  file: logs.txt
