package application.controllers.dtos

import application.enums.Role
import io.swagger.annotations.ApiModelProperty

class UserDTO(

        @ApiModelProperty("Unique email of a user")
        var email: String,

        @ApiModelProperty("First calendarName of a user")
        var firstName: String,

        @ApiModelProperty("Last calendarName of a user")
        var lastName: String,

        @ApiModelProperty("Password of a user")
        var password: String,

        @ApiModelProperty("Pin-code of a user")
        var pin: String,

        @ApiModelProperty("A set of access roles this user has")
        var roles: Set<Role> = setOf(),

        @ApiModelProperty("If a user is enabled or not")
        var enabled: Boolean = true,

        @ApiModelProperty("A list of calendars owned by this user by name")
        var calendars: MutableList<String> = mutableListOf(),

        @ApiModelProperty("A list of calendars shared with this user")
        var accessibleCalendars: MutableList<Long> = mutableListOf(),

        @ApiModelProperty("Autogenerated id of a user")
        var id: String? = null

)